const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:8765',out=process.argv[3];if(out)fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,...(process.env.PW_CHANNEL==='none'?{}:{channel:process.env.PW_CHANNEL||'msedge'})}),page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/ai-education-chapter5/');await page.waitForSelector('[data-ready=true]');
 const data=await page.evaluate(()=>fetch('/data/lectures/ai-education/5.json').then(r=>r.json()));assert.equal(data.slides.length,70);assert.equal(data.slides.filter(s=>s.sourceSlide).length,64);assert.equal(data.sourceVersion,'v4');
 const go=async n=>{await page.evaluate(n=>location.hash='slide-'+n,n);await page.waitForFunction(n=>Number(document.querySelector('#ce-page').value)===n,n)};
 const lab=async name=>go(data.slides.findIndex(s=>s.lab===name)+1);
 for(let n=1;n<=70;n++){
  await go(n);await page.waitForFunction(()=>[...document.querySelectorAll('#ae-slide img')].every(im=>im.complete&&im.naturalWidth>0));assert(await page.locator('#ce-loading').isHidden());
  if(data.slides[n-1].kind!=='lab'){
   const bad=await page.locator('#ae-slide').evaluate(el=>[...el.querySelectorAll('.ae-run')].filter(r=>parseFloat(r.style.top)<-1||parseFloat(r.style.top)+parseFloat(r.style.lineHeight)>parseFloat(el.style.height)+3).map(r=>r.textContent));assert.deepEqual(bad,[],`text outside slide ${n}`);
   for(const im of await page.locator('.ch5-picture').all()){await im.click();assert(await page.locator('#ch5-image-dialog').isVisible());await page.keyboard.press('d');assert.equal(new URL(page.url()).hash,'#slide-'+n);await page.keyboard.press('Escape')}
  }
  if(out)await page.locator('#ce-stage').screenshot({path:path.join(out,`${String(n).padStart(2,'0')}.png`)});
 }
 await lab('accuracy');assert(await page.locator('[data-example-result]').isHidden());assert(await page.locator('[data-reveal]').isDisabled());await page.locator('[data-prediction]').selectOption('50% 이상 80% 미만');await page.locator('[data-reveal]').click();assert.match(await page.locator('[data-example-result]').innerText(),/75.0%/);
 await page.locator('[data-count="1"]').fill('80');assert(await page.locator('[data-example-result]').isHidden());assert(await page.locator('[data-reveal]').isDisabled());await page.locator('[data-prediction]').selectOption('50% 미만');await page.locator('[data-reveal]').click();assert.match(await page.locator('[data-example-result]').innerText(),/30.0%/);
 await page.locator('[data-count="0"]').fill('-1');await page.locator('[data-prediction]').selectOption('50% 미만');await page.locator('[data-reveal]').click();assert.match(await page.locator('[data-example-result]').innerText(),/정수/);
 await lab('colab');assert(await page.locator('[data-colab-open]').isHidden());await page.locator('[data-prediction]').selectOption('모델 B');await page.locator('[data-field=reason]').fill('모델 B의 학습 자료에 어두운 사진이 더 많기 때문이다');assert(await page.locator('[data-colab-open]').isVisible());assert.equal(await page.locator('[data-colab-open] a.ch5-button').getAttribute('href'),'https://colab.research.google.com/github/jinsung4069/jinsung4069.github.io/blob/main/data/lectures/ai-education-ch5-bias-lab.ipynb');
 for(const [k,v] of [['ABright','94.4'],['ADark','54.7'],['BBright','92.8'],['BDark','73.6']])await page.locator(`[data-num=${k}]`).fill(v);const colabText=await page.locator('[data-colab-result]').innerText();assert.match(colabText,/\+39\.7%p/);assert.match(colabText,/\+18\.9%p/);assert.match(colabText,/-1\.6%p/);
 await page.locator('[data-num=ADark]').fill('120');assert.match(await page.locator('[data-colab-result]').innerText(),/0 이상 100 이하/);await page.locator('[data-num=ADark]').fill('54.7');
 await lab('abstention');assert.match(await page.locator('[data-abstention-metrics]').innerText(),/85.7%/);assert.match(await page.locator('[data-abstention-metrics]').innerText(),/12장/);await page.locator('[data-threshold]').fill('100');assert.match(await page.locator('[data-abstention-metrics]').innerText(),/계산 불가/);assert.match(await page.locator('[data-abstention-metrics]').innerText(),/40장/);
 await lab('model-card');await page.locator('[data-field=purpose]').fill('수업 내 숫자 인식 검토');await page.locator('[data-decision]').selectOption('보류');const download=page.waitForEvent('download');await page.locator('[data-download]').click();const file=await download;assert.equal(file.suggestedFilename(),'인공지능윤리_활동기록.json');const stream=await file.createReadStream();let raw='';for await(const chunk of stream)raw+=chunk;const saved=JSON.parse(raw);assert.equal(saved.modelCard.decision,'보류');assert.equal(saved.colab.prediction,'모델 B');assert.equal(saved.colab.BDark,'73.6');
 await page.reload();await page.waitForSelector('[data-ready=true]');assert.equal(await page.locator('[data-field=purpose]').inputValue(),'수업 내 숫자 인식 검토');
 await lab('quiz');assert(await page.locator('[data-quiz-result]').isHidden());for(const a of [1,0,0,0,1]){await page.locator(`[data-answer="${a}"]`).click();assert.match(await page.locator('[data-quiz-result]').innerText(),/맞습니다/);if(await page.locator('[data-quiz-next]').isEnabled())await page.locator('[data-quiz-next]').click()}
 await go(1);await page.locator('#ce-next').focus();await page.keyboard.press('d');assert.equal(new URL(page.url()).hash,'#slide-2');await page.keyboard.press('a');assert.equal(new URL(page.url()).hash,'#slide-1');await page.keyboard.press('f');await page.waitForFunction(()=>!!document.fullscreenElement);await page.keyboard.press('f');await page.waitForFunction(()=>!document.fullscreenElement);
 await page.locator('#ce-open-toc').click();await page.locator('#ce-search').fill('개인정보');assert((await page.locator('#ce-toc button:visible').count())>0);await page.keyboard.press('Escape');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});for(let n=1;n<=70;n++){await go(n);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`mobile overflow ${width}, ${n}`)}}
 await page.setViewportSize({width:1440,height:1050});const printPage=await browser.newPage({viewport:{width:1440,height:1000}});printPage.on('pageerror',e=>errors.push(e.message));await printPage.goto(base+'/ai-education-chapter5/?lecture-print=1');await printPage.evaluate(()=>LecturePrint.prepare());assert.equal(await printPage.locator('.lecture-print-sheet').count(),70);if(out)await printPage.pdf({path:path.join(out,'chapter5.pdf'),preferCSSPageSize:true,printBackground:true});
 await page.goto(base+'/ai-education/');assert.equal(await page.locator('a[href="/ai-education-chapter5/"]').count(),1);
 for(const chapter of [1,3,4]){await page.goto(base+`/ai-education-chapter${chapter}/`);await page.waitForSelector('[data-ready=true]');assert(await page.locator('#ce-loading').isHidden())}
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 64 original slides, 6 activities, preserved images, prediction gates, Colab record, calculations, export, persistence, keyboard, fullscreen, mobile, 70 print sheets and prior decks.');
})().catch(e=>{console.error(e);process.exit(1)});
